package EmployeeManagementSystem;


/**
* EmployeeManagementSystem/Location.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/g-harel/Documents/dev/DEMS/DistributedEmployeeManagementSystem/src/EmployeeManagementSystem.idl
* Tuesday, October 23, 2018 1:08:41 PM EDT
*/

public interface Location extends LocationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Location
