package DEMS;


/**
* DEMS/LocationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/g-harel/Documents/dev/DEMS/DistributedEmployeeManagementSystem/src/DEMS.idl
* Saturday, October 20, 2018 2:46:42 o'clock PM EDT
*/

public interface LocationOperations 
{
  String address ();
  boolean createMRecord (String managerID, String firstName, String lastName, int employeeID, String mailID, String project, String location);
  boolean createERecord (String managerID, String firstName, String lastName, int employeeID, String mailID, String projectID);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
  void shutdown ();
} // interface LocationOperations
