package DEMS;


/**
* DEMS/Location.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/g-harel/Documents/dev/DEMS/DistributedEmployeeManagementSystem/src/DEMS.idl
* Sunday, October 21, 2018 3:24:12 o'clock PM EDT
*/

public interface Location extends LocationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Location
