package DEMS;


/**
* DEMS/Location.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/g-harel/Documents/dev/DEMS/DistributedEmployeeManagementSystem/src/DEMS.idl
* Monday, October 22, 2018 9:15:51 o'clock AM EDT
*/

public interface Location extends LocationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Location
