#!/bin/bash

source lib

function list {
    echo "ls"
}

function create_employee {
    echo "er
    John
    Doe
    123456
    john.doe@example.com
    P00000"
}

function create_manager {
    echo "mr
    Samantha
    Smith
    654321
    samantha.smith@example.com
    P11111
    Project 1
    Alex Richard
    $(fallback "$1" "CA")"
}

function edit {
    echo "ed
    $(fallback "$1" "ER00000")
    $(fallback "$2" "mailID")
    $(fallback "$3" "test@example.com")"
}

function move {
    echo "test"
}

function finish {
    echo "ex"
}
