#!/bin/bash

clear

CMD=$1

ORB_PORT=1051

SRC_PATH=$(pwd)/src
BIN_PATH=$(pwd)/bin

IDL_NAME=DEMS
CLIENT_CLASS=Client
SERVER_CLASS=Server

function printStep {
    echo -e "\n >> \e[1;35m$1\e[0m\n"
}

function cmdDone {
    if [[ $CMD == "$1" ]]; then
        exit 0
    fi
}

function sketchyWait {
    sleep 0.314159
}

function runServer {
    java $SERVER_CLASS -ORBInitialPort $ORB_PORT "$@" &
}

printStep "compiling idl interface"
rm -rf $SRC_PATH/$IDL_NAME
idlj -fall -td $SRC_PATH $SRC_PATH/$IDL_NAME.idl

cmdDone "gen"

printStep "compiling source"
mkdir -p bin
javac -d $BIN_PATH $SRC_PATH/*.java $SRC_PATH/**/*.java

cmdDone "build"

printStep "starting naming service"
pkill orbd
sketchyWait
orbd -ORBInitialPort $ORB_PORT&
sketchyWait

cd $BIN_PATH

printStep "starting server"
runServer

sketchyWait

printStep "starting client"
java $CLIENT_CLASS -ORBInitialPort $ORB_PORT

sketchyWait

kill $(jobs -p)
