#!/bin/bash

ORB_PORT=1051

SRC_PATH=$(pwd)/src
BIN_PATH=$(pwd)/bin
LOG_PATH=$BIN_PATH/log
ORBD_BIN_PATH=$BIN_PATH/orbd

CORBA_PKG=corba
WS_PKG=webservice
IDL_NAME=EmployeeManagementSystem
JAX_NAME=LocationWS
CLIENT_CLASS=Client
SERVER_CLASS=Server

clear
# rm -rf $BIN_PATH
# mkdir -p $BIN_PATH

function step {
    echo -e "\n >> \e[1;35m$1\e[0m\n"
}

function fallback {
    if [[ $1 != "" ]]; then
      echo "$1"
    else
      echo "$2"
    fi
}

function delay {
    sleep $(fallback $1 0.3141519)
}

function compile_java {
    javac -d $BIN_PATH -cp src:. $SRC_PATH/**/*.java
}

function cleanup {
    while [[ $(ps T | grep -P "java .*$CLIENT_CLASS [A-Z]{2}") != "" ]]; do
        delay
    done

    step "cleaning up"

    pkill orbd
    rm -rf $ORBD_BIN_PATH

    rogues=$(ps T | grep -oP "^\s*\d+(?=.*java .*($SERVER_CLASS|$CLIENT_CLASS) [A-Z]{2})" | grep -oP "\w+")
    if [[ $rogues != "" ]]; then
        kill $rogues
    fi
}

trap cleanup EXIT
