#!/bin/bash

function codegen {
    echo "" &> /dev/null
}

function setup {
    echo "" &> /dev/null
}

function run_server {
    pushd $BIN_PATH >/dev/null

    >&2 echo "starting server:" "$@"
    java $WS_PKG.$SERVER_CLASS "$@" >/dev/null

    popd >/dev/null
}

function run_client {
    pushd $BIN_PATH >/dev/null

    >&2 echo "starting client:" "$@"
    java $WS_PKG.$CLIENT_CLASS "$@"

    popd >/dev/null
}