#!/bin/bash

source lib
source commands

source run/servers

step "running concurrent scenario"

run_client "CA00000" << EOF >/dev/null &
$(create_employee)
$(move "ER00000" "US")
$(finish)
EOF

run_client "US00000" << EOF >/dev/null &
$(create_manager)
$(edit "MR00001" "project.name" "Project ABC")
$(finish)
EOF

delay

run_client "UK00000" << EOF >/dev/null &
$(list)
$(finish)
EOF
